### ISSUE TITLE
Images with certain color pallettes can not be blurred

### ISSUE THREAD

**Issue by dsiebes** [ptrck/wagtail-lazyimages#1]
Great work here, thank you for sharing! I noticed one little bug, ImageFilter.GaussianBlur will return "ValueError: image has wrong mode" if certain images are used. Here is a workaround to apply before attempting to blur:

 if img.mode in ["1", "P"]:
        lazy_img = img.convert(mode="RGB")

**Comment by ptrck** [comment]
Thanks for the heads up! I'll look into it.

**Comment by ptrck** [comment]
Fixed in 64cca315dc
