### ISSUE TITLE
Create rendition for placeholder images?

### ISSUE THREAD

**Issue by tomdyson** [ptrck/wagtail-lazyimages#2]
Hey @ptrck, this looks great! Before using it in production, we'd be worried that resizing (potentially large) images from (potentially remote) storage backends might impact page performance. Would you consider creating renditions for your placeholder images?

**Comment by ptrck** [comment]
@tomdyson thanks for your input. Can you elaborate your concerns a bit? The templatetag is already taking a rendition as parameter. It's doing the same thing wagtail's `{% image ... %}` tag would do, with the difference that it generates an additional 128x128 image from the generated rendition.

**Comment by yatesrates** [comment]
Heyo @ptrck,
I think @tomdyson might be referring to the thumbnail not being saved as a rendition and being generated each time.
The placeholder image is also generated fairly manually vs using wagtail renditions.
It seems like it might be more wagtaily to use get_rendition

**Comment by ptrck** [comment]
Gotcha. Thank's for the explanation @yatesrates. I finally had some time to look into this. The reason why I don't generate renditions here is the blur filter. I just can't get around manipulating and saving the image via Pillow. So resizing and blurring manually seems like the most straight forward approach to me.

I did optimize it in f146e2569 though: The placeholder image will now only be generated if it doesn't exist yet (or the original rendition has changed). Does that remove your concerns about performance? @tomdyson

**Comment by ptrck** [comment]
I'm closing this for now since the core issue regarding performance is resolved.

**Comment by tomdyson** [comment]
> Does that remove your concerns about performance? @tomdyson

Belatedly: yes, it does, thanks @ptrck!
