### ISSUE TITLE
Any way of integrating this with Wagtail's RichTextField?

### ISSUE THREAD

**Issue by JoeWHoward** [ptrck/wagtail-lazyimages#3]
I'm looking to utilize this inside of Wagtail's RichTextField editor, my initial thoughts on it are to hook in using the register_extra_features call and to add a "lazy image" option, but I'm not entirely sure that would work and can use some input/suggestions.

**Comment by ptrck** [comment]
Hey there,

you want to lazy load images that come from a rich text field (rendered by the `|richtext` filter) is that correct? This is outside of the current scope of this project.

I think the easiest way to achieve this is by subclassing wagtail's [`Format` class](https://github.com/wagtail/wagtail/blob/master/wagtail/images/formats.py) and overriding the `image_to_html` Method. There you need to manipulate the attributes of the image tag (`src` and `data-src`) and provide the placeholder url (similarly to what I've done in the [template tag](https://github.com/ptrck/wagtail-lazyimages/blob/master/wagtail_lazyimages/templatetags/lazyimages_tags.py#L51)).

I'd be happy to merge a pull request in case you find a way to make this easier with a helper method or a `LazyFormat` or something like that.

Hope this helps.
